services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  worker:
    image: leorfy/worker:latest
    environment:
      REDIS_HOST: redis
      DB_HOST: 10.0.11.250
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres