services:
  vote:
    image: leorfy/vote:latest
    ports:
      - "8080:80"
    environment:
      REDIS_HOST: "10.0.11.223"

  result:
    image: leorfy/result:latest
    ports:
      - "8081:80"
    environment:
      PG_HOST: "10.0.11.250"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"