[bastion]
instance_a ansible_host=34.255.197.144 ansible_ssh_common_args=''

[worker]
instance_b ansible_host=10.0.2.93

[database]
instance_c ansible_host=10.0.2.177

[worker:vars]
ansible_ssh_common_args='-o ForwardAgent=yes -o ProxyJump=ec2-user@34.255.197.144'

[database:vars]
ansible_ssh_common_args='-o ForwardAgent=yes -o ProxyJump=ec2-user@34.255.197.144'

[all:vars]
ansible_user=ec2-user
ansible_ssh_private_key_file=/Users/tatianatudor/Desktop/devops/tatiana-project1.pem